# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  orleans-cache:
    image: orleans-cache
    build:
      context: .
      dockerfile: Orleans/Orleans.SiloGrpc/Dockerfile
    ports:
      - 8081
      - 8082
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  fake-datasource:
    image: fake-datasource
    build:
      context: .
      dockerfile: CalculationService/Dockerfile
    ports:
      - 8085
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8085
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
